### ISSUE TITLE
Define Core Members and their duties

### ISSUE THREAD

**Issue by cheapwebmonkey** [civicdata/bylaws#4]

**Comment by OrthoStice** [comment]
Is the idea that core members are the worker bees?  I.e they make sure announcements are out, volunteer positions are covered, space is reserved etc...

**Comment by OrthoStice** [comment]
Questions: 
Is core membership distinct from membership?
Do we need to set minimums and maximums on size as either precise numbers or percentage of membership?
Do we need to make clear in bylaws that all hackathons and participation in electronic communication is open to public regardless of membership status?
And of course: How do we include a focus on diversity in composition of core membership?

**Comment by rkahne** [comment]
In my mind: 

* Membership = attached to the group in a public way
* Core Membership = Willing to help organize, lead, and make/enact policies and event for the group.
* Board = Decision making body with final determination of issues unresolved at Core level.

**Comment by cityresearch** [comment]
i'm probably missing some context here, so please correct me if so... 
- But if the bylaws under discussion are intended to be the bylaws for the nonprofit CDA, then they would be the governing document for the CDA Board of Directors (the body responsible for the nonprofit). 
- Volunteer coordination (Core membership, membership, etc) would be a program area managed by CDA, but not something to be included in the nonprofit bylaws as a specific program area that would be subject to change over time given resources, organizational directions, etc.

**Comment by OrthoStice** [comment]
I see, so bylaws don't need to address core membership?  
If not, should there be another doc concerning program areas?
Of course, with the understanding that bylaws are more pressing currently.

**Comment by cityresearch** [comment]
this whole Core Membership thing is coming over from the Code for America brigade program. It makes a lot of sense as a organizational framework for a volunteer group. http://brigade.codeforamerica.org/brigade/organize/

**Comment by OrthoStice** [comment]
that completely makes sense to me.  i don't know how this should officially be handled but my feeling is we close the issue without defining core membership in bylaws but readdress elsewhere.

**Comment by OrthoStice** [comment]
Are there any guidelines for how core membership and the board interact that should be addressed in bylaws?

**Comment by cityresearch** [comment]
the CFA Code of Conduct for Brigades seems to address a lot of the pertinent issues... these could also be made to apply to the interface with the non profit board. For example (very loosley), core members have a lot of latitude but the board/E.D. can shut things down that aren't in the spirit of the CDA Mission. https://docs.google.com/document/d/19bN5RWK5nQTpz0mHUViHrzHiommBUAMSztwNRzUcxYo/edit#heading=h.9ei58w5t1ccw

**Comment by mgottholsen** [comment]
Closing this issue in favor of the operations document that is already part of this repo.
