### ISSUE TITLE
Address voluntary abstain

### ISSUE THREAD

**Issue by leighPri** [civicdata/bylaws#7]
The idea is that a board member will be designated as the "voluntary" abstainer, the position rotating to different board members each quarter. This would have no effect normally, but in the event a board member must vacate their seat, the designated abstainer member will abstain from votes until the seat is filled (or until the responsibility rotates with the quarter).

Perhaps have two designates, a primary and a secondary, in the event that the primary abstainer is the member who vacates the board. Or instead have a schedule drawn up and then in the event that the designated abstainer vacates the next board member in line will take up the position (and in this case the schedule would move up a quarter to ensure no one is abstaining for more than a quarter at at a time).

All this is to ensure that there is an odd number of votes available at all times to prevent ties or deadlocks. Obviously, all up for discussion.

**Comment by rkahne** [comment]
Is this an issue to address the potentiality that there might be an even number of board seats and therefore raises the prospect of a tie?

**Comment by leighPri** [comment]
Correct
